//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int ID_List { get; set; }
        public Nullable<int> ID_Theme { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> Readiness_Degree { get; set; }
        public Nullable<int> Student_ID { get; set; }
        public Nullable<System.DateTime> Work_submition_date { get; set; }
        public Nullable<int> Half_Year { get; set; }
        public Nullable<int> ID_Disciline { get; set; }
    
        public virtual Semester Semester { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual Students Students { get; set; }
    }
}
