//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class delivery_of_term_papers_by_studentsEntities : DbContext
    {
        private static delivery_of_term_papers_by_studentsEntities _context;

        public delivery_of_term_papers_by_studentsEntities()
            : base("name=delivery_of_term_papers_by_studentsEntities")
        {
        }

        public static delivery_of_term_papers_by_studentsEntities GetContext()
        {
            if (_context == null)
                _context = new delivery_of_term_papers_by_studentsEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Discipline> Discipline { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<Semester> Semester { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Theme> Theme { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
